services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      - AUTH_SECRET=secret
      - AUTH_URL=http://localhost:3000
      - DATABASE_URL=file:/data/db.sqlite
    env_file:
      - .env.local
    volumes:
      - ./data:/data
      - ./src/generated:/app/src/generated
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
            - generated/
        - action: rebuild
          path: package.json
        - action: sync+restart
          path: prisma
          target: /app/prisma
        - action: sync+restart
          path: ./src/app/api
          target: /app/src/app/api
