name: docker-build

on:
  push:
    branches:
      - main
      - renovate/*
    tags:
      - 'v*'
  pull_request:

jobs:
  docker:
    runs-on: docker
    container:
      image: ghcr.io/di0ik/forgejo_runner_container:main@sha256:c4667f2702c32b91b4c92db2ff20739edd00409a44a691c0598cf4a09a47743a
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: git.dominikstahl.dev
          username: ${{ secrets.DOER }}
          password: ${{ secrets.TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

      - name: Get the Ref
        id: get-ref
        uses: https://github.com/ankitvgupta/ref-to-tag-action@master
        with:
          ref: ${{ github.ref }}
          head_ref: ${{ github.head_ref }}

      - name: lowercase repo name
        run: |
          echo "REPO=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')" >>${GITHUB_ENV}

      - name: Build and push (pull_request)
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        if: github.event_name == 'pull_request'
        with:
          push: true
          tags: git.dominikstahl.dev/${{ env.REPO }}:${{ steps.get-ref.outputs.tag}}
          cache-from: type=registry,ref=git.dominikstahl.dev/${{ env.REPO }}:buildcache

      - name: Build and push (push_tag)
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        if: github.event_name == 'push' && github.ref_type == 'tag'
        with:
          push: true
          tags: git.dominikstahl.dev/${{ env.REPO }}:${{ steps.get-ref.outputs.tag }},git.dominikstahl.dev/${{ env.REPO }}:latest
          cache-from: type=registry,ref=git.dominikstahl.dev/${{ env.REPO }}:buildcache

      - name: Build and push (push_branch)
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        if: github.event_name == 'push' && github.ref_type == 'branch'
        with:
          push: true
          tags: git.dominikstahl.dev/${{ env.REPO }}:${{ steps.get-ref.outputs.tag }}
          cache-from: type=registry,ref=git.dominikstahl.dev/${{ env.REPO }}:buildcache
          cache-to: type=registry,ref=git.dominikstahl.dev/${{ env.REPO }}:buildcache,mode=max

      - name: Clean up Docker
        run: |
          docker buildx prune --filter=until=48h -f
