name: docker-build

on:
  push:
    branches:
      - main
      - renovate/*
    tags:
      - 'v*'
  pull_request:

jobs:
  docker:
    runs-on: docker
    container:
      image: ghcr.io/di0ik/forgejo_runner_container:main@sha256:672aee9a5dfc35531db3a218ad9486eb5c5d7d9ac10bdcba13110470c10403ee
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: git.dominikstahl.dev
          username: ${{ secrets.DOER }}
          password: ${{ secrets.TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3

      - name: Get the Ref
        id: get-ref
        uses: https://github.com/ankitvgupta/ref-to-tag-action@master
        with:
          ref: ${{ github.ref }}
          head_ref: ${{ github.head_ref }}

      - name: lowercase repo name
        run: |
          echo "REPO=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')" >>${GITHUB_ENV}

      - name: Build and push (pull_request)
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6
        if: github.event_name == 'pull_request'
        with:
          push: true
          tags: git.dominikstahl.dev/${{ env.REPO }}:${{ steps.get-ref.outputs.tag}}

      - name: Build and push (push_tag)
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6
        if: github.event_name == 'push' && github.ref_type == 'tag'
        with:
          push: true
          tags: git.dominikstahl.dev/${{ env.REPO }}:${{ steps.get-ref.outputs.tag }},git.dominikstahl.dev/${{ env.REPO }}:latest

      - name: Build and push (push_branch)
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6
        if: github.event_name == 'push' && github.ref_type == 'branch'
        with:
          push: true
          tags: git.dominikstahl.dev/${{ env.REPO }}:${{ steps.get-ref.outputs.tag }}

      - name: Clean up Docker
        run: |
          docker buildx prune --filter=until=48h -f
