name: docker-build

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:

jobs:
  docker:
    runs-on: docker
    steps:
      - name: Install Docker
        run: |
          apt-get update
          apt-get install -y ca-certificates curl
          install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
          chmod a+r /etc/apt/keyrings/docker.asc
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
          apt-get update
          apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: git.dominikstahl.dev
          username: ${{ secrets.DOER }}
          password: ${{ secrets.TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push (pull_request)
        uses: docker/build-push-action@v6
        if: github.event_name == 'pull_request'
        with:
          push: true
          tags: ${{ github.repository }}:sha_${{ github.sha }},${{ github.repository }}:pr_${{ github.head_ref }}

      - name: Build and push (push_tag)
        uses: docker/build-push-action@v6
        if: github.event_name == 'push' && github.ref_type == 'tag'
        with:
          push: true
          tags: ${{ github.repository }}:${{ github.ref_name }},${{ github.repository }}:latest

      - name: Build and push (push_branch)
        uses: docker/build-push-action@v6
        if: github.event_name == 'push' && github.ref_type == 'branch'
        with:
          push: true
          tags: ${{ github.repository }}:sha_${{ github.sha }},${{ github.repository }}:main
